### ISSUE TITLE
Option to exclude godeps directories

### ISSUE THREAD

**Issue by f1yegor** [KyleBanks/goggles#32]
I can see some godeps files and other unrelated stuff like

- Godeps/_workspace/src/github.com/prometheus/client_golang/prometheus
- github.com/prometheus/prometheus_cli/.build/gopath/src/github.com/prometheus/common/expfmt
- .build/gopath/src/github.com/Sirupsen/logrus

**Comment by KyleBanks** [comment]
Definitely, there's a slice of ignored paths [here](https://github.com/KyleBanks/goggles/blob/master/util.go) we could add those too (Godeps/ and .build/) since both would be something everyone would likely ignore.

In the future maybe a more customizable ignore system would be helpful but for now I think this is okay.

**Comment by f1yegor** [comment]
Looks good!
